// Phase 15: Claude Code Integration Tests
//
// 15.1 CLAUDE.md auto-generation
// 15.2 Auto-memory session management
// 15.3 Subagent coordination

use evif_core::{EvifPlugin, RadixMountTable};
use evif_mcp::{EvifMcpServer, McpServerConfig};
use evif_plugins::MemFsPlugin;
use evif_rest::create_routes;
use serde_json::json;
use std::sync::{Arc, OnceLock};

static EVIF_URL: OnceLock<String> = OnceLock::new();

fn ensure_evif_url() -> String {
    EVIF_URL
        .get_or_init(|| {
            let (tx, rx) = std::sync::mpsc::channel();

            std::thread::spawn(move || {
                let runtime = tokio::runtime::Runtime::new().expect("runtime");
                runtime.block_on(async move {
                    let mount_table = Arc::new(RadixMountTable::new());
                    let context_mem = Arc::new(MemFsPlugin::new());
                    context_mem.mkdir("/L0", 0o755).await.expect("mkdir L0");
                    context_mem.mkdir("/L1", 0o755).await.expect("mkdir L1");
                    context_mem
                        .create("/L0/current", 0o644)
                        .await
                        .expect("create current");
                    context_mem
                        .create("/L1/decisions.md", 0o644)
                        .await
                        .expect("create decisions");
                    let pipes_mem = Arc::new(MemFsPlugin::new());
                    let skills_mem = Arc::new(MemFsPlugin::new());
                    mount_table
                        .mount("/context".to_string(), context_mem as Arc<dyn EvifPlugin>)
                        .await
                        .expect("mount context");
                    mount_table
                        .mount("/pipes".to_string(), pipes_mem as Arc<dyn EvifPlugin>)
                        .await
                        .expect("mount pipes");
                    mount_table
                        .mount("/skills".to_string(), skills_mem as Arc<dyn EvifPlugin>)
                        .await
                        .expect("mount skills");

                    let app = create_routes(mount_table);
                    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
                        .await
                        .expect("bind");
                    let address = listener.local_addr().expect("local addr");
                    tx.send(format!("http://{}", address)).expect("send url");
                    axum::serve(listener, app.into_make_service())
                        .await
                        .expect("serve");
                });
            });

            rx.recv().expect("receive url")
        })
        .clone()
}

fn make_server() -> Arc<EvifMcpServer> {
    let config = McpServerConfig {
        evif_url: ensure_evif_url(),
        ..McpServerConfig::default()
    };
    EvifMcpServer::new(config)
}

async fn wait_for_tools(server: &evif_mcp::EvifMcpServer) -> Vec<evif_mcp::Tool> {
    for _ in 0..30 {
        let tools = server.list_tools().await;
        if tools.len() >= 20 {
            return tools;
        }
        tokio::time::sleep(tokio::time::Duration::from_millis(50)).await;
    }
    server.list_tools().await
}

// ── Phase 15.1: CLAUDE.md auto-generation ─────────────────────────────────

#[tokio::test]
async fn mcp15_claude_md_tool_registered() {
    let server = make_server();
    let tools = wait_for_tools(&server).await;

    let names: Vec<&str> = tools.iter().map(|t| t.name.as_str()).collect();
    assert!(
        names.contains(&"evif_claude_md_generate"),
        "evif_claude_md_generate should be registered"
    );
}

#[tokio::test]
async fn mcp15_claude_md_default_params() {
    let server = make_server();
    let tools = wait_for_tools(&server).await;

    let tool = tools.iter().find(|t| t.name == "evif_claude_md_generate");
    assert!(tool.is_some(), "Tool should exist");

    let schema = &tool.unwrap().input_schema;
    assert!(schema.get("properties").is_some());
    assert!(schema
        .get("properties")
        .unwrap()
        .get("project_path")
        .is_some());
    assert!(schema
        .get("properties")
        .unwrap()
        .get("include_skills")
        .is_some());
    assert!(schema
        .get("properties")
        .unwrap()
        .get("include_context")
        .is_some());
}

#[tokio::test]
async fn mcp15_claude_md_returns_content() {
    let server = make_server();

    let result = server
        .call_tool("evif_claude_md_generate", json!({}))
        .await
        .expect("Tool should be callable");

    assert!(result.get("content").is_some(), "Should return content");
    let content = result["content"].as_str().unwrap();
    assert!(content.contains("# Project Context"), "Should have header");
    assert!(
        content.contains("Auto-generated by EVIF MCP Server"),
        "Should be auto-generated"
    );
}

#[tokio::test]
async fn mcp15_claude_md_with_skills_disabled() {
    let server = make_server();

    let result = server
        .call_tool(
            "evif_claude_md_generate",
            json!({
                "include_skills": false,
                "include_context": false
            }),
        )
        .await
        .expect("Tool should be callable");

    let content = result["content"].as_str().unwrap();
    assert!(content.contains("# Project Context"));
    assert!(
        !content.contains("## Skills"),
        "Skills section should be omitted"
    );
}

// ── Phase 15.2: Session management ────────────────────────────────────────

#[tokio::test]
async fn mcp15_session_tools_registered() {
    let server = make_server();
    let tools = wait_for_tools(&server).await;

    let names: Vec<&str> = tools.iter().map(|t| t.name.as_str()).collect();
    assert!(
        names.contains(&"evif_session_save"),
        "evif_session_save should be registered"
    );
    assert!(
        names.contains(&"evif_session_list"),
        "evif_session_list should be registered"
    );
}

#[tokio::test]
async fn mcp15_session_save_l0() {
    let server = make_server();

    let result = server
        .call_tool(
            "evif_session_save",
            json!({
                "level": "L0",
                "content": "Working on Phase 15 integration tests"
            }),
        )
        .await
        .expect("Tool should be callable");

    assert_eq!(result["status"], "saved");
    assert_eq!(result["level"], "L0");
    assert_eq!(result["path"], "/context/L0/current");
}

#[tokio::test]
async fn mcp15_session_save_l1_with_summary() {
    let server = make_server();

    let result = server
        .call_tool(
            "evif_session_save",
            json!({
                "level": "L1",
                "content": "Implemented Phase 15.1-15.3 MCP tools",
                "summary": "MCP Enhancement"
            }),
        )
        .await
        .expect("Tool should be callable");

    assert_eq!(result["status"], "saved");
    assert_eq!(result["level"], "L1");
    assert_eq!(result["path"], "/context/L1/decisions.md");
}

#[tokio::test]
async fn mcp15_session_list() {
    let server = make_server();

    let result = server
        .call_tool("evif_session_list", json!({}))
        .await
        .expect("Tool should be callable");

    // Should return a valid response (even if empty)
    assert!(result.get("data").is_some() || result.get("error").is_some() || result.is_object());
}

#[tokio::test]
async fn mcp15_session_list_filtered() {
    let server = make_server();

    let result = server
        .call_tool(
            "evif_session_list",
            json!({
                "level": "L1",
                "limit": 5
            }),
        )
        .await
        .expect("Tool should be callable");

    assert!(result.is_object());
}

// ── Phase 15.3: Subagent coordination ──────────────────────────────────────

#[tokio::test]
async fn mcp15_subagent_tools_registered() {
    let server = make_server();
    let tools = wait_for_tools(&server).await;

    let names: Vec<&str> = tools.iter().map(|t| t.name.as_str()).collect();
    assert!(
        names.contains(&"evif_subagent_create"),
        "evif_subagent_create should be registered"
    );
    assert!(
        names.contains(&"evif_subagent_send"),
        "evif_subagent_send should be registered"
    );
    assert!(
        names.contains(&"evif_subagent_list"),
        "evif_subagent_list should be registered"
    );
}

#[tokio::test]
async fn mcp15_subagent_create() {
    let server = make_server();

    let result = server
        .call_tool(
            "evif_subagent_create",
            json!({
                "name": "test-agent-1",
                "task": "Review the codebase for bugs",
                "context_path": "/context/L0/current"
            }),
        )
        .await
        .expect("Tool should be callable");

    assert_eq!(result["status"], "created");
    assert_eq!(result["name"], "test-agent-1");
    assert_eq!(result["context_path"], "/context/L0/current");
    assert!(result["input"].as_str().unwrap().contains("test-agent-1"));
}

#[tokio::test]
async fn mcp15_subagent_create_requires_name() {
    let server = make_server();

    let result = server
        .call_tool(
            "evif_subagent_create",
            json!({
                "task": "Some task without name"
            }),
        )
        .await;

    let err = result.expect_err("Should fail without name");
    assert!(err.contains("name") || err.contains("Missing"));
}

#[tokio::test]
async fn mcp15_subagent_send() {
    let server = make_server();

    // Try to send (pipe may not exist, but tool should be callable)
    let result = server
        .call_tool(
            "evif_subagent_send",
            json!({
                "name": "test-agent-2",
                "message": "Update: Please check the tests"
            }),
        )
        .await;

    // Should either succeed or return graceful error (not panic)
    match result {
        Ok(resp) => {
            assert_eq!(resp["status"], "sent");
        }
        Err(e) => {
            // Graceful error if pipe doesn't exist or server unavailable
            assert!(
                e.contains("not found") || e.contains("Failed") || e.contains("connection"),
                "Should be graceful error, got: {}",
                e
            );
        }
    }
}

#[tokio::test]
async fn mcp15_subagent_list() {
    let server = make_server();

    let result = server
        .call_tool("evif_subagent_list", json!({}))
        .await
        .expect("Tool should be callable");

    // Should return list of pipes (even if empty)
    assert!(result.is_object());
}
